apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
    version: "1.0"
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: microservice-istio-apache:latest        
        imagePullPolicy: Never        
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    version: "1.0"
  name: postgres
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.15       
        imagePullPolicy: Never        
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "dbuser"
        - name: POSTGRES_PASSWORD
          value: "dbpass"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d/
      initContainers:
      - name: initialize-postgres
        image: alpine:3
        volumeMounts:
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d/
        command: ["/bin/sh"]
        env:
        - name: POSTGRES_USER
          value: "dbuser"
        args:
          - "-c"
          - |
            echo "#!/bin/bash
            set -e

            psql -v ON_ERROR_STOP=1 --username \"$POSTGRES_USER\" <<-EOSQL
                CREATE DATABASE dbshipping;
                GRANT ALL PRIVILEGES ON DATABASE dbshipping TO dbuser;
                CREATE DATABASE dbinvoicing;
                GRANT ALL PRIVILEGES ON DATABASE dbinvoicing TO dbuser;
                CREATE DATABASE dborder;
                GRANT ALL PRIVILEGES ON DATABASE dborder TO dbuser;
                CREATE DATABASE dbbonus;
                GRANT ALL PRIVILEGES ON DATABASE dbbonus TO dbuser;
            EOSQL" > /docker-entrypoint-initdb.d/init-user-db.sh
            chmod 0755 /docker-entrypoint-initdb.d/init-user-db.sh
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-init
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: apache
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: NodePort

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apache
spec:
  hosts:
  - "*"
  gateways:
  - microservice-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: apache.default.svc.cluster.local        
